/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoginInfo: typeof import('./src/components/LoginInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCom: typeof import('./src/components/TestCom.vue')['default']
    UserDialog: typeof import('./src/views/record/components/userDialog.vue')['default']
    WebSocket: typeof import('./src/components/WebSocket.vue')['default']
  }
}
