/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Function: typeof import('./src/views/record/study-ts/components/Function.vue')['default']
    ReturnType: typeof import('./src/views/record/study-ts/components/ReturnType.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCom: typeof import('./src/components/TestCom.vue')['default']
    UserDialog: typeof import('./src/views/record/components/userDialog.vue')['default']
  }
}
